### ISSUE TITLE
AttributeError when running MLP on Cerebro

### ISSUE THREAD

**Issue by agupta01** [ADALabUCSD/cerebro-system#25]
I'm attempting to run Cerebro GridSearch on an MLP with 4 inputs and 1 output. The dataset has the below schema:

```
root
 |-- Temperature: double (nullable = true)
 |-- Occupancy: double (nullable = true)
 |-- Temperature_1: double (nullable = true)
 |-- Temperature_2: double (nullable = true)
 |-- Temperature_3: double (nullable = true)
```
The objective is to predict `Occupancy` with the Temperature columns.

When we run the cerebro `model_selection.fit` method, we get this error (on each Worker):
```
Traceback (most recent call last):
  File "/Users/arunavgupta/anaconda3/envs/cerebro/lib/python3.7/site-packages/cerebro_dl-1.0.0-py3.7.egg/cerebro/tune/base.py", line 200, in fit
    result = self._fit_on_prepared_data(metadata)
  File "/Users/arunavgupta/anaconda3/envs/cerebro/lib/python3.7/site-packages/cerebro_dl-1.0.0-py3.7.egg/cerebro/tune/grid.py", line 86, in _fit_on_prepared_data
    return _fit_on_prepared_data(self, metadata)
  File "/Users/arunavgupta/anaconda3/envs/cerebro/lib/python3.7/site-packages/cerebro_dl-1.0.0-py3.7.egg/cerebro/tune/grid.py", line 226, in _fit_on_prepared_data
    self.label_cols)
  File "/Users/arunavgupta/anaconda3/envs/cerebro/lib/python3.7/site-packages/cerebro_dl-1.0.0-py3.7.egg/cerebro/backend/spark/backend.py", line 260, in train_for_one_epoch
    raise Exception(status.sub_epoch_result['error'])
Exception: in user code:

    /Users/arunavgupta/anaconda3/envs/cerebro/lib/python3.7/site-packages/cerebro_dl-1.0.0-py3.7.egg/cerebro/keras/spark/util.py:155 prep  *
        tuple(
    /Users/arunavgupta/anaconda3/envs/cerebro/lib/python3.7/site-packages/cerebro_dl-1.0.0-py3.7.egg/cerebro/keras/spark/util.py:148 get_col_from_row_fn  *
        return getattr(row, col)

    AttributeError: 'petastorm_schema_view_view' object has no attribute 'input_layer'
```

Where `input_layer` is the name of the first layer in the model.

It seems that targeting various versions of pyspark (2.4.4, 2.4.8, and 3.2.0) as well as downloading cerebro from source and from pypi does not seem to fix this issue. Any ideas on how to get around this issue are appreciated, I will post the relevant source code in a comment to this issue.

**Comment by agupta01** [comment]
Source code:

```python
# SparkEstimator doesn't implement _fit, so this gets around that not implemented error.
class Model(SparkEstimator):
    def _fit(self, dataset):
        pass
        # print(dataset)
        # assert False


def estimator_gen_fn(params):
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Input(shape=4, name="input_layer"))
    model.add(tf.keras.layers.Dense(1, input_dim=4))
    model.add(tf.keras.layers.Activation("sigmoid"))

    optimizer = tf.keras.optimizers.SGD(lr=params["lr"])
    loss = "mse"

    estimator = Model(
        model=model, optimizer=optimizer, loss=loss, metrics=["acc"], batch_size=8
    )

    return estimator


spark = SparkSession.builder.getOrCreate()

df = (
    spark.read.option("header", True)
    .option("inferSchema", True)
    .parquet("./data/dataTraining.parquet")
)


prepped = prep_data_spark(
    df.select("date", "Temperature", "Occupancy"),
    3,
    1,
    "mean",
    time_col="date",
    value_col="Temperature",
    label_col="Occupancy",
)
print("Data Loaded.")

backend = SparkBackend(spark_context=spark.sparkContext, num_workers=2)
store = LocalStore(prefix_path="/Users/arunavgupta/Documents/FA21/cse234/data/")

train_df, test_df = prepped.drop(F.col("date")).randomSplit([0.8, 0.2])
train_df = train_df.repartition(2)

search_space = {"lr": hp_choice([0.01, 0.001, 0.0001])}

model_selection = GridSearch(
    backend,
    store,
    estimator_gen_fn,
    search_space,
    num_epochs=10,
    evaluation_metric="loss",
    label_columns=["Occupancy"],
    feature_columns=["Temperature", "Temperature_1", "Temperature_2", "Temperature_3"],
    verbose=1,
)

model = model_selection.fit(train_df)

**Comment by scnakandala** [comment]
Cerebro matches the input layers to features by name. The model seems to expect a single vector input called 'input_layer'.
But the data has 4 features with different names. I think that is the reason for the failure.

**Comment by agupta01** [comment]
Thanks! It appears this worked. In order to make the vector input I used:

```python
from pyspark.ml.feature import VectorAssembler

assembler = VectorAssembler(inputCols=['Temperature', 'Temperature_1', 'Temperature_2', 'Temperature_3'], outputCol='features')

prepped = assembler.transform(prepped)
```

And then changed the layer name to 'features' to get it to accept that column.
